name:                hpffp
version:             0.1.0.0
github:              "wtjerry/haskell_firstSteps/hpffp"
license:             GPL-3
author:              "wtjerry"
maintainer:          "na@na.na"
copyright:           "wtjerry"

description:         Please see the README on GitHub at <https://github.com/wtjerry/haskell_firstSteps#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hpffp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - hpffp

tests:
  hpffp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - hpffp
