name:                codewars
version:             0.1.0.0
github:              "wtjerry/codewars"
license:             BSD3
author:              "wtjerry"
maintainer:          "na@na.na"
copyright:           "wtjerry"

description:         Please see the README on GitHub at <https://github.com/wtjerry/haskell_firstSteps>

dependencies:
- base
- containers
- mtl
- split

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -fno-warn-type-defaults

executables:
  codewars-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    - -Wall
    - -fno-warn-type-defaults
    dependencies:
    - codewars

tests:
  codewars-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -fno-warn-type-defaults
    dependencies:
    - codewars
    - hspec
    - QuickCheck
